#!/usr/bin/env bash


################################################################################
### Head: Url
##

# * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl
# * https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/

##
### Tail: Url
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
THE_CMD_FILE_NAME=$(basename $0)
##
### Tail: Init
################################################################################


################################################################################
### Head: Util_Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2;
	fi
}

##
### Head: Util_Debug
################################################################################


################################################################################
### Head: Base
##
find_dir_path () {
	if [ ! -d $(dirname -- "$1") ]; then
		dirname -- "$1"
		return 1
	fi
	echo $(cd -P -- "$(dirname -- "$1")" && pwd -P)
}

##THIS_BASE_DIR_PATH=$(find_dir_path $0)

## $ export DEBUG_SS_CTRL=true
is_debug () {
	if [ "$DEBUG_SS_CTRL" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/../.")
	THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/.")

	THE_CMD_VERSION='0.1'

	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"

	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
		THE_CMD_FILE_NAME="style-switch-xfce"
	fi

	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/$THE_CMD_FILE_NAME"

	## https://github.com/samwhelp/play-ubuntu-20.04-plan/blob/master/project/style-xfce/style-switch/style-switch-xfce
	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/note-about-manjaro/gh-pages/_demo/project/style-xfce/style-switch/style-switch-xfce'


	THE_TMP_DIR_PATH="/tmp"


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"


	THE_PROFILE_DIR_NAME=".${THE_CMD_FILE_NAME}-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"


}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"

	util_debug_echo "THE_CMD_FILE_NAME=$THE_CMD_FILE_NAME"
	util_debug_echo "THE_CMD_FILE_PATH=$THE_CMD_FILE_PATH"
	util_debug_echo "THE_CMD_DIR_PATH=$THE_CMD_DIR_PATH"

	util_debug_echo "THE_SELF_UPDATE_URL=$THE_SELF_UPDATE_URL"


	util_debug_echo "THE_TMP_DIR_PATH=$THE_TMP_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"



	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util_SubCmd
##

sub_cmd_find_function_name () {
	echo "sub_run_$1"
}

##
### Tail: Util_SubCmd
################################################################################


################################################################################
### Head: Util_Self_Update
##

util_make_bin_dir () {
	mkdir -p "$HOME/bin"
}

util_make_tmp_dir () {
	THE_TMP_DIR_PATH="/tmp/tmp.$$.$RANDOM"
	mkdir "$THE_TMP_DIR_PATH"
}

util_self_update_download_to_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	wget -c "$THE_SELF_UPDATE_URL" -O "$tmp_file_path"

}

util_self_update_install_from_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	echo "install -m 755 $tmp_file_path $THE_CMD_FILE_PATH"
	install -m 755 "$tmp_file_path" "$THE_CMD_FILE_PATH"

}

util_self_update_check_cmd_exists () {

	if ! [ -f "$THE_CMD_FILE_PATH" ]; then ## file not exists
		return 0
	fi


	echo "File is exists:" "$THE_CMD_FILE_PATH"
	echo

	echo "Try to backup:"
	echo

	local now=$(date +%Y%m%d_%s)
	local bak_dir_path="${THE_CMD_FILE_PATH}.bak"
	local bak_file_path="${bak_dir_path}/${THE_CMD_FILE_NAME}.bak.$now"

	mkdir -p $bak_dir_path

	mv -v "$THE_CMD_FILE_PATH" "${bak_file_path}"

	if [ "$?" != "0" ]; then
		echo
		echo 'Backup Failure!'
		exit 1
	fi

	echo

	return 0
}

util_self_update_print_version () {
	echo
	echo "Current Version:"

	"$THE_CMD_FILE_PATH" version
}

util_self_update () {

	util_make_bin_dir

	util_make_tmp_dir

	util_self_update_download_to_tmp_dir

	util_self_update_check_cmd_exists && util_self_update_install_from_tmp_dir


	util_self_update_print_version

}


main_version () {
	echo $THE_CMD_VERSION
}

util_self_actions () {
	grep '^sub_run' "${THE_CMD_FILE_PATH}" | cut -d ' ' -f 1 | awk -F 'sub_run_' '{print $2}' | sort -u
}

##
### Tail: Util_Self_Update
################################################################################


################################################################################
### Head: Sys
##

sys_xfce_set_wm_theme () {

	local wm_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
	## <property name="theme" type="string" value="Numix"/>

	xfconf-query -c 'xfwm4' -p '/general/theme' -s "$wm_theme"
	echo "xfconf-query -c 'xfwm4' -p '/general/theme' -s '$wm_theme'"

}

sys_xfce_get_wm_theme () {

	xfconf-query -c 'xfwm4' -p '/general/theme'

}

sys_xfce_set_ui_theme () {

	local ui_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="ThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s "$ui_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s '$ui_theme'"

}

sys_xfce_get_ui_theme () {

	xfconf-query -c 'xsettings' -p '/Net/ThemeName'

}

sys_xfce_set_icon_theme () {

	local icon_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="IconThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s "$icon_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s '$icon_theme'"

}

sys_xfce_get_icon_theme () {

	xfconf-query -c 'xsettings' -p '/Net/IconThemeName'

}

sys_xfce_set_cursor_theme () {

	local cursor_theme_name="$1"
	local cursor_theme_size="$2"

	if [ "none${cursor_theme_name}" = "none" ]; then
		cursor_theme_name="default"
	fi

	if [ "none${cursor_theme_size}" = "none" ]; then
		cursor_theme_size="24"
	fi

	#echo $cursor_theme_name
	#echo $cursor_theme_size
	#return


	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

	## <property name="CursorThemeName" type="string" value="default"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="breeze_cursors"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="xcursor-breeze"/>
	## <property name="CursorThemeSize" type="int" value="24"/>


	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s '$cursor_theme_name'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s "$cursor_theme_name"

	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s '$cursor_theme_size'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s "$cursor_theme_size"


}

sys_xfce_get_cursor_theme () {
	local name=$(xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName')

	local size=$(xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize')

	echo "${name} ${size}"
}

sys_xfce_get_all () {

	local wm_theme=$(sys_xfce_get_wm_theme)
	local ui_theme=$(sys_xfce_get_ui_theme)
	local icon_theme=$(sys_xfce_get_icon_theme)
	local cursor_theme=$(sys_xfce_get_cursor_theme)

	echo "wm_theme: ${wm_theme}"
	echo "ui_theme: ${ui_theme}"
	echo "icon_theme: ${icon_theme}"
	echo "cursor_theme: ${cursor_theme}"

}


sys_xfce_get_all_default () {

	local wm_theme=$(sys_xfce_get_wm_theme_default)
	local ui_theme=$(sys_xfce_get_ui_theme_default)
	local icon_theme=$(sys_xfce_get_icon_theme_default)
	local cursor_theme=$(sys_xfce_get_cursor_theme_default)
	local cursor_theme_for_dark=$(sys_xfce_get_cursor_theme_default_for_dark)
	local cursor_theme_for_light=$(sys_xfce_get_cursor_theme_default_for_light)

	echo "wm_theme: ${wm_theme}"
	echo "ui_theme: ${ui_theme}"
	echo "icon_theme: ${icon_theme}"
	echo "cursor_theme: ${cursor_theme}"
	echo "cursor_theme_for_dark: ${cursor_theme_for_dark}"
	echo "cursor_theme_for_light: ${cursor_theme_for_light}"

}

sys_xfce_set_all_default () {

	sys_xfce_set_wm_theme_default
	sys_xfce_set_ui_theme_default
	sys_xfce_set_icon_theme_default
	sys_xfce_set_cursor_theme_default

}

sys_xfce_get_wm_theme_default () {

	echo 'Matcha-sea'
}

sys_xfce_set_wm_theme_default () {

	sys_xfce_set_wm_theme $(sys_xfce_get_wm_theme_default)

}

sys_xfce_get_ui_theme_default () {

	echo 'Matcha-sea'

}

sys_xfce_set_ui_theme_default () {

	sys_xfce_set_ui_theme $(sys_xfce_get_ui_theme_default)

}

sys_xfce_get_icon_theme_default () {

	echo 'Papirus-Maia'

}

sys_xfce_set_icon_theme_default () {

	sys_xfce_set_icon_theme $(sys_xfce_get_icon_theme_default)

}

sys_xfce_get_cursor_theme_default () {

	echo 'xcursor-breeze' 24

}

sys_xfce_set_cursor_theme_default () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default)

}

sys_xfce_get_cursor_theme_default_for_dark () {

	echo 'xcursor-breeze' 24

}

sys_xfce_set_cursor_theme_default_for_dark () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default_for_dark)
}

sys_xfce_get_cursor_theme_default_for_light () {

	echo 'xcursor-breeze-snow' 24

}

sys_xfce_set_cursor_theme_default_for_light () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default_for_light)

}

##
### Tail: Sys
################################################################################


################################################################################
### Head: Model theme_matcha_dark_aliz
##

theme_matcha_dark_aliz_config_wm_theme () {

	sys_xfce_set_wm_theme 'Matcha-dark-aliz'

}

theme_matcha_dark_aliz_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-aliz'

}

theme_matcha_dark_aliz_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

theme_matcha_dark_aliz_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_matcha_dark_aliz () {
	#echo "theme_matcha_dark_aliz"
	#echo "$@"


	theme_matcha_dark_aliz_config_wm_theme
	theme_matcha_dark_aliz_config_ui_theme
	theme_matcha_dark_aliz_config_icon_theme
	theme_matcha_dark_aliz_config_cursor_theme

}

##
### Tail: Model theme_matcha_dark_aliz
################################################################################


################################################################################
### Head: Model theme_matcha_dark_azul
##

theme_matcha_dark_azul_config_wm_theme () {

	sys_xfce_set_wm_theme 'Matcha-dark-azul'

}

theme_matcha_dark_azul_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-azul'

}

theme_matcha_dark_azul_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

theme_matcha_dark_azul_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_matcha_dark_azul () {
	#echo "theme_matcha_dark_azul"
	#echo "$@"


	theme_matcha_dark_azul_config_wm_theme
	theme_matcha_dark_azul_config_ui_theme
	theme_matcha_dark_azul_config_icon_theme
	theme_matcha_dark_azul_config_cursor_theme

}

##
### Tail: Model theme_matcha_dark_azul
################################################################################


################################################################################
### Head: Model theme_matcha_dark_sea
##

theme_matcha_dark_sea_config_wm_theme () {

	sys_xfce_set_wm_theme 'Matcha-dark-sea'

}

theme_matcha_dark_sea_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-sea'

}

theme_matcha_dark_sea_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

theme_matcha_dark_sea_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_matcha_dark_sea () {
	#echo "theme_matcha_dark_sea"
	#echo "$@"


	theme_matcha_dark_sea_config_wm_theme
	theme_matcha_dark_sea_config_ui_theme
	theme_matcha_dark_sea_config_icon_theme
	theme_matcha_dark_sea_config_cursor_theme

}

##
### Tail: Model theme_matcha_dark_sea
################################################################################


################################################################################
### Head: Model theme_numix
##

theme_numix_config_wm_theme () {

	sys_xfce_set_wm_theme 'Numix'

}

theme_numix_config_ui_theme () {

	sys_xfce_set_ui_theme 'Numix'

}

theme_numix_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix-Circle'

}

theme_numix_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_numix () {
	#echo "theme_numix"
	#echo "$@"


	theme_numix_config_wm_theme
	theme_numix_config_ui_theme
	theme_numix_config_icon_theme
	theme_numix_config_cursor_theme

}

##
### Tail: Model theme_numix
################################################################################


################################################################################
### Head: Model theme_numix_blue
##

theme_numix_blue_config_wm_theme () {

	sys_xfce_set_wm_theme 'NumixBlue'

}

theme_numix_blue_config_ui_theme () {

	sys_xfce_set_ui_theme 'NumixBlue'

}

theme_numix_blue_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix'

}

theme_numix_blue_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_numix_blue () {
	#echo "theme_numix_blue"
	#echo "$@"


	theme_numix_blue_config_wm_theme
	theme_numix_blue_config_ui_theme
	theme_numix_blue_config_icon_theme
	theme_numix_blue_config_cursor_theme

}

##
### Tail: Model theme_numix_blue
################################################################################


################################################################################
### Head: Model theme_obsidian_2_gray
##

theme_obsidian_2_gray_config_wm_theme () {

	sys_xfce_set_wm_theme 'Obsidian-2-Gray'

}

theme_obsidian_2_gray_config_ui_theme () {

	sys_xfce_set_ui_theme 'Obsidian-2-Gray'

}

theme_obsidian_2_gray_config_icon_theme () {

	sys_xfce_set_icon_theme 'Black-Frost-Suru'

}

theme_obsidian_2_gray_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_obsidian_2_gray () {
	#echo "theme_obsidian_2_gray"
	#echo "$@"


	theme_obsidian_2_gray_config_wm_theme
	theme_obsidian_2_gray_config_ui_theme
	theme_obsidian_2_gray_config_icon_theme
	theme_obsidian_2_gray_config_cursor_theme

}

##
### Tail: Model theme_obsidian_2_gray
################################################################################


################################################################################
### Head: Model theme_shades_of_gray
##

theme_shades_of_gray_config_wm_theme () {

	sys_xfce_set_wm_theme 'Shades-of-gray'

}

theme_shades_of_gray_config_ui_theme () {

	sys_xfce_set_ui_theme 'Shades-of-gray'

}

theme_shades_of_gray_config_icon_theme () {

	sys_xfce_set_icon_theme 'Black-Frost-Suru'

}

theme_shades_of_gray_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

theme_shades_of_gray () {
	#echo "theme_shades_of_gray"
	#echo "$@"


	theme_shades_of_gray_config_wm_theme
	theme_shades_of_gray_config_ui_theme
	theme_shades_of_gray_config_icon_theme
	theme_shades_of_gray_config_cursor_theme

}

##
### Tail: Model theme_shades_of_gray
################################################################################


################################################################################
### Head: Model ui_honda_super_cub_wm_pastel_dark
##

ui_honda_super_cub_wm_pastel_dark_config_wm_theme () {

	sys_xfce_set_wm_theme 'Pastel_Dark'

}

ui_honda_super_cub_wm_pastel_dark_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

ui_honda_super_cub_wm_pastel_dark_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

ui_honda_super_cub_wm_pastel_dark_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ui_honda_super_cub_wm_pastel_dark () {
	#echo "ui_honda_super_cub_wm_pastel_dark"
	#echo "$@"


	ui_honda_super_cub_wm_pastel_dark_config_wm_theme
	ui_honda_super_cub_wm_pastel_dark_config_ui_theme
	ui_honda_super_cub_wm_pastel_dark_config_icon_theme
	ui_honda_super_cub_wm_pastel_dark_config_cursor_theme

}

##
### Tail: Model ui_honda_super_cub_wm_pastel_dark
################################################################################


################################################################################
### Head: Model ui_honda_super_cub_wm_rgapsline
##

ui_honda_super_cub_wm_rgapsline_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsLine'

}

ui_honda_super_cub_wm_rgapsline_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

ui_honda_super_cub_wm_rgapsline_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

ui_honda_super_cub_wm_rgapsline_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ui_honda_super_cub_wm_rgapsline () {
	#echo "ui_honda_super_cub_wm_rgapsline"
	#echo "$@"


	ui_honda_super_cub_wm_rgapsline_config_wm_theme
	ui_honda_super_cub_wm_rgapsline_config_ui_theme
	ui_honda_super_cub_wm_rgapsline_config_icon_theme
	ui_honda_super_cub_wm_rgapsline_config_cursor_theme

}

##
### Tail: Model ui_honda_super_cub_wm_rgapsline
################################################################################


################################################################################
### Head: Model wm_chandelier_ui_honda_super_cub
##

wm_chandelier_ui_honda_super_cub_config_wm_theme () {

	sys_xfce_set_wm_theme 'Chandelier'

}

wm_chandelier_ui_honda_super_cub_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

wm_chandelier_ui_honda_super_cub_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

wm_chandelier_ui_honda_super_cub_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

wm_chandelier_ui_honda_super_cub () {
	#echo "wm_chandelier_ui_honda_super_cub"
	#echo "$@"


	wm_chandelier_ui_honda_super_cub_config_wm_theme
	wm_chandelier_ui_honda_super_cub_config_ui_theme
	wm_chandelier_ui_honda_super_cub_config_icon_theme
	wm_chandelier_ui_honda_super_cub_config_cursor_theme

}

##
### Tail: Model wm_chandelier_ui_honda_super_cub
################################################################################


################################################################################
### Head: Model wm_rgaps_line_ui_matcha_dark_aliz
##

wm_rgaps_line_ui_matcha_dark_aliz_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsLine'

}

wm_rgaps_line_ui_matcha_dark_aliz_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-aliz'

}

wm_rgaps_line_ui_matcha_dark_aliz_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

wm_rgaps_line_ui_matcha_dark_aliz_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

wm_rgaps_line_ui_matcha_dark_aliz () {
	#echo "wm_rgaps_line_ui_matcha_dark_aliz"
	#echo "$@"


	wm_rgaps_line_ui_matcha_dark_aliz_config_wm_theme
	wm_rgaps_line_ui_matcha_dark_aliz_config_ui_theme
	wm_rgaps_line_ui_matcha_dark_aliz_config_icon_theme
	wm_rgaps_line_ui_matcha_dark_aliz_config_cursor_theme

}

##
### Tail: Model wm_rgaps_line_ui_matcha_dark_aliz
################################################################################


################################################################################
### Head: Model wm_rgaps_line_nobuttons_ui_matcha_dark_aliz
##

wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsLineNoButtons'

}

wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-aliz'

}

wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

wm_rgaps_line_nobuttons_ui_matcha_dark_aliz () {
	#echo "wm_rgaps_line_nobuttons_ui_matcha_dark_aliz"
	#echo "$@"


	wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_wm_theme
	wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_ui_theme
	wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_icon_theme
	wm_rgaps_line_nobuttons_ui_matcha_dark_aliz_config_cursor_theme

}

##
### Tail: Model wm_rgaps_line_nobuttons_ui_matcha_dark_aliz
################################################################################


################################################################################
### Head: Model wm_rgaps_blend_ui_matcha_dark_aliz
##

wm_rgaps_blend_ui_matcha_dark_aliz_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsBlend'

}

wm_rgaps_blend_ui_matcha_dark_aliz_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-aliz'

}

wm_rgaps_blend_ui_matcha_dark_aliz_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

wm_rgaps_blend_ui_matcha_dark_aliz_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

wm_rgaps_blend_ui_matcha_dark_aliz () {
	#echo "wm_rgaps_blend_ui_matcha_dark_aliz"
	#echo "$@"


	wm_rgaps_blend_ui_matcha_dark_aliz_config_wm_theme
	wm_rgaps_blend_ui_matcha_dark_aliz_config_ui_theme
	wm_rgaps_blend_ui_matcha_dark_aliz_config_icon_theme
	wm_rgaps_blend_ui_matcha_dark_aliz_config_cursor_theme

}

##
### Tail: Model wm_rgaps_blend_ui_matcha_dark_aliz
################################################################################


################################################################################
### Head: Model wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz
##

wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsBlendNoButtons'

}

wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_ui_theme () {

	sys_xfce_set_ui_theme 'Matcha-dark-aliz'

}

wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz () {
	#echo "wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz"
	#echo "$@"


	wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_wm_theme
	wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_ui_theme
	wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_icon_theme
	wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz_config_cursor_theme

}

##
### Tail: Model wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz
################################################################################


################################################################################
### Head: SubCmd
##

sub_run_help () {
	main_usage "$@"
}

sub_run_version () {
	main_version "$@"
}

sub_run_self_update () {
	util_self_update "$@"
}

sub_run_self_actions () {
	util_self_actions "$@"
}

sub_run_default () {
	#echo "sub_run_default"
	sys_xfce_set_all_default
}




sub_run_theme_matcha_dark_aliz () {
	#echo "sub_run_theme_matcha_dark_aliz"
	theme_matcha_dark_aliz "$@"
}


sub_run_theme_matcha_dark_azul () {
	#echo "sub_run_theme_matcha_dark_azul"
	theme_matcha_dark_azul "$@"
}


sub_run_theme_matcha_dark_sea () {
	#echo "sub_run_theme_matcha_dark_sea"
	theme_matcha_dark_sea "$@"
}


sub_run_theme_numix () {
	#echo "sub_run_theme_numix"
	theme_numix "$@"
}


sub_run_theme_numix_blue () {
	#echo "sub_run_theme_numix_blue"
	theme_numix_blue "$@"
}


sub_run_theme_obsidian_2_gray () {
	#echo "sub_run_theme_obsidian_2_gray"
	theme_obsidian_2_gray "$@"
}


sub_run_theme_shades_of_gray () {
	#echo "sub_run_theme_shades_of_gray"
	theme_shades_of_gray "$@"
}


sub_run_ui_honda_super_cub_wm_pastel_dark () {
	#echo "sub_run_ui_honda_super_cub_wm_pastel_dark"
	ui_honda_super_cub_wm_pastel_dark "$@"
}


sub_run_ui_honda_super_cub_wm_rgapsline () {
	#echo "sub_run_ui_honda_super_cub_wm_rgapsline"
	ui_honda_super_cub_wm_rgapsline "$@"
}


sub_run_wm_chandelier_ui_honda_super_cub () {
	#echo "sub_run_wm_chandelier_ui_honda_super_cub"
	wm_chandelier_ui_honda_super_cub "$@"
}


sub_run_wm_rgaps_line_ui_matcha_dark_aliz () {
	#echo "sub_run_wm_rgaps_line_ui_matcha_dark_aliz"
	wm_rgaps_line_ui_matcha_dark_aliz "$@"
}


sub_run_wm_rgaps_line_nobuttons_ui_matcha_dark_aliz () {
	#echo "sub_run_wm_rgaps_line_nobuttons_ui_matcha_dark_aliz"
	wm_rgaps_line_nobuttons_ui_matcha_dark_aliz "$@"
}


sub_run_wm_rgaps_blend_ui_matcha_dark_aliz () {
	#echo "sub_run_wm_rgaps_blend_ui_matcha_dark_aliz"
	wm_rgaps_blend_ui_matcha_dark_aliz "$@"
}


sub_run_wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz () {
	#echo "sub_run_wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz"
	wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz "$@"
}

##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF
Usage:
	$ $cmd_name [action]

Example:

	## help

		$ $cmd_name
		$ $cmd_name help

	## version

		$ $cmd_name version

	## self_update

		$ $cmd_name self_update

	## self_actions

		$ $cmd_name self_actions

	## theme

		$ $cmd_name default


		$ $cmd_name theme_matcha_dark_aliz

		$ $cmd_name theme_matcha_dark_azul

		$ $cmd_name theme_matcha_dark_sea

		$ $cmd_name theme_numix

		$ $cmd_name theme_numix_blue

		$ $cmd_name theme_obsidian_2_gray

		$ $cmd_name theme_shades_of_gray

		$ $cmd_name ui_honda_super_cub_wm_pastel_dark

		$ $cmd_name ui_honda_super_cub_wm_rgapsline

		$ $cmd_name wm_chandelier_ui_honda_super_cub

		$ $cmd_name wm_rgaps_line_ui_matcha_dark_aliz

		$ $cmd_name wm_rgaps_line_nobuttons_ui_matcha_dark_aliz

		$ $cmd_name wm_rgaps_blend_ui_matcha_dark_aliz

		$ $cmd_name wm_rgaps_blend_nobuttons_ui_matcha_dark_aliz


Debug:
	$ export DEBUG_SS_CTRL=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local function_name=$(sub_cmd_find_function_name "$sub_cmd")

	## if ! command -v $function_name > /dev/null; then
	if ! type -p $function_name > /dev/null; then
		util_debug_echo "[Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"

		echo
		main_run_default_sub_cmd "$@"
		return 1
	fi

	"$function_name" "$@" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
