
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make all'
	@echo
	@echo '	$$ make theme-numix'
	@echo
	@echo '	$$ make theme-numix-blue'
	@echo
	@echo '	$$ make theme-obsidian-2-gray'
	@echo
	@echo '	$$ make theme-shades-of-gray'
	@echo
	@echo '	$$ make theme-honda-super-cub-wm-pastel-dark'
	@echo
	@echo '	$$ make theme-honda-super-cub-wm-rgapsline'
	@echo
	@echo '	$$ make theme-honda-super-cub-wm-chandelier'
	@echo


.PHONY: help


all: theme-numix theme-numix-blue theme-obsidian-2-gray theme-shades-of-gray theme-honda-super-cub-wm-rgapsline theme-honda-super-cub-wm-chandelier theme-honda-super-cub-wm-pastel-dark

.PHONY: all


theme-numix:
	make -C theme-numix install
.PHONY: theme-numix


theme-numix-blue:
	make -C theme-numix-blue install
.PHONY: theme-numix-blue


theme-obsidian-2-gray:
	make -C theme-obsidian-2-gray install
.PHONY: theme-obsidian-2-gray


theme-shades-of-gray:
	make -C theme-shades-of-gray install
.PHONY: theme-shades-of-gray


theme-honda-super-cub-wm-pastel-dark:
	make -C theme-honda-super-cub-wm-pastel-dark install
.PHONY: theme-honda-super-cub-wm-pastel-dark


theme-honda-super-cub-wm-rgapsline:
	make -C theme-honda-super-cub-wm-rgapsline install
.PHONY: theme-honda-super-cub-wm-rgapsline


theme-honda-super-cub-wm-chandelier:
	make -C theme-honda-super-cub-wm-chandelier install
.PHONY: theme-honda-super-cub-wm-chandelier
