
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make all'
	@echo
	@echo '	$$ make theme-numix-blue'
	@echo
	@echo '	$$ make theme-honda-super-cub-wm-pastel-dark'
	@echo


.PHONY: help


all: theme-numix-blue theme-honda-super-cub-wm-pastel-dark

.PHONY: all


theme-numix-blue:
	make -C theme-numix-blue install
.PHONY: theme-numix-blue


theme-honda-super-cub-wm-pastel-dark:
	make -C theme-honda-super-cub-wm-pastel-dark install
.PHONY: theme-honda-super-cub-wm-pastel-dark


