
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make all'
	@echo
	@echo '	$$ make theme-numix'
	@echo
	@echo '	$$ make theme-numix-blue'
	@echo
	@echo '	$$ make theme-obsidian-2-gray'
	@echo
	@echo '	$$ make theme-shades-of-gray'
	@echo
	@echo '	$$ make wm-pastel-dark-ui-honda-super-cub'
	@echo
	@echo '	$$ make theme-honda-super-cub-wm-rgapsline'
	@echo
	@echo '	$$ make wm-chandelier-ui-honda-super-cub'
	@echo
	@echo '	$$ make wm-chandelier-ui-matcha-dark-aliz'
	@echo
	@echo '	$$ make wm-rgaps-line-ui-matcha-dark-aliz'
	@echo
	@echo '	$$ make wm-rgaps-line-nobuttons-ui-matcha-dark-aliz'
	@echo
	@echo '	$$ make wm-rgaps-blend-ui-matcha-dark-aliz'
	@echo
	@echo '	$$ make wm-rgaps-blend-nobuttons-ui-matcha-dark-aliz'
	@echo


.PHONY: help


all: theme-numix theme-numix-blue theme-obsidian-2-gray theme-shades-of-gray theme-honda-super-cub-wm-rgapsline wm-chandelier-ui-honda-super-cub wm-chandelier-ui-matcha-dark-aliz wm-pastel-dark-ui-honda-super-cub wm-rgaps-line-ui-matcha-dark-aliz wm-rgaps-line-nobuttons-ui-matcha-dark-aliz wm-rgaps-blend-ui-matcha-dark-aliz wm-rgaps-blend-nobuttons-ui-matcha-dark-aliz

.PHONY: all


theme-numix:
	make -C theme-numix install
.PHONY: theme-numix


theme-numix-blue:
	make -C theme-numix-blue install
.PHONY: theme-numix-blue


theme-obsidian-2-gray:
	make -C theme-obsidian-2-gray install
.PHONY: theme-obsidian-2-gray


theme-shades-of-gray:
	make -C theme-shades-of-gray install
.PHONY: theme-shades-of-gray


wm-pastel-dark-ui-honda-super-cub:
	make -C wm-pastel-dark-ui-honda-super-cub install
.PHONY: wm-pastel-dark-ui-honda-super-cub


theme-honda-super-cub-wm-rgapsline:
	make -C theme-honda-super-cub-wm-rgapsline install
.PHONY: theme-honda-super-cub-wm-rgapsline


wm-chandelier-ui-honda-super-cub:
	make -C wm-chandelier-ui-honda-super-cub install
.PHONY: wm-chandelier-ui-honda-super-cub


wm-chandelier-ui-matcha-dark-aliz:
	make -C wm-chandelier-ui-matcha-dark-aliz install
.PHONY: wm-chandelier-ui-matcha-dark-aliz


wm-rgaps-line-ui-matcha-dark-aliz:
	make -C wm-rgaps-line-ui-matcha-dark-aliz install
.PHONY: wm-rgaps-line-ui-matcha-dark-aliz


wm-rgaps-line-nobuttons-ui-matcha-dark-aliz:
	make -C wm-rgaps-line-nobuttons-ui-matcha-dark-aliz install
.PHONY: wm-rgaps-line-nobuttons-ui-matcha-dark-aliz


wm-rgaps-blend-ui-matcha-dark-aliz:
	make -C wm-rgaps-blend-ui-matcha-dark-aliz install
.PHONY: wm-rgaps-blend-ui-matcha-dark-aliz


wm-rgaps-blend-nobuttons-ui-matcha-dark-aliz:
	make -C wm-rgaps-blend-nobuttons-ui-matcha-dark-aliz install
.PHONY: wm-rgaps-blend-nobuttons-ui-matcha-dark-aliz
